### PR TITLE
Refactor/styling final pass

### PR DESCRIPTION
**Pull request by tenthwalker**
# Description
Final passthrough for FitLit part 1 to clean up CSS/HTML to match final rubric specifications and final design adjustments to match all data sets applied by the DOM update functions.

# Contributors
@tenthwalker @BrendanTurner1 @ericahagle @butlertree 

# Checklist
- [x] My PR has an appropriately descriptive and concise title.
- [x] My PR denotes any/all team members who contributed to it.
- [x] My code follows the Turing Style Guides and best practices.
- [x] I ran the code locally and verified that there are no visible errors.
- [x] refactor: My PR clearly describes what code I'm refactoring and why.

### CODE REVIEW

**Comment by butlertree** [comment]
Very nice work on all of the clean up!  It came together very well.

**Review by butlertree — APPROVED** [review]
It looks great!  I don't have anything to add.

**Review by BrendanTurner1 — APPROVED** [review]
Looks awesome. Thanks for c leaning this up.

**Review by ericahagle — APPROVED** [review]
This looks so goooood. I'm glad we all worked together on a call to talk out what the final result should be. And you absolutely crushed implementing the feedback, @tenthwalker! Kudos all around. 😎 🌴

**Pull request merged**
